// Copyright 2004-2018 Castle Project - http://www.castleproject.org/
// 
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// 
//     http://www.apache.org/licenses/LICENSE-2.0
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// This file was automatically generated by 'ModelFakes.tt', please don't edit manually.

namespace Castle.Facilities.AspNetCore.Tests.Fakes;

using System;

using Castle.Core;
using Castle.MicroKernel.Registration;
using Castle.Windsor;

using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Razor.TagHelpers;
using Microsoft.Extensions.DependencyInjection;

public partial class OpenOptions {}
public partial class ClosedOptions {}

public interface IDisposableObservable 
{
	bool Disposed { get;set; }
	int DisposedCount { get;set; }
}

public interface IWeakReferenceObservable 
{
	bool HasReference { get; }
}

public partial class ServiceProviderOnlyTransient : IWeakReferenceObservable 
{
	private readonly WeakReference _reference;

	public ServiceProviderOnlyTransient()
	{
		_reference = new WeakReference(this, false);
	}

	public bool HasReference => _reference.IsAlive;
}

public partial class ServiceProviderOnlyTransientGeneric<T> : ServiceProviderOnlyTransient { }

public partial class ServiceProviderOnlyTransientDisposable : ServiceProviderOnlyTransient, IDisposable, IDisposableObservable, IWeakReferenceObservable
{ 
	public bool Disposed { get;set; }
	public int DisposedCount { get;set; }
	public void Dispose() { Disposed = true; DisposedCount++; } 
}

public partial class ServiceProviderOnlyScoped : IWeakReferenceObservable 
{
	private readonly WeakReference _reference;

	public ServiceProviderOnlyScoped()
	{
		_reference = new WeakReference(this, false);
	}

	public bool HasReference => _reference.IsAlive;
}

public partial class ServiceProviderOnlyScopedGeneric<T> : ServiceProviderOnlyScoped { }

public partial class ServiceProviderOnlyScopedDisposable : ServiceProviderOnlyScoped, IDisposable, IDisposableObservable, IWeakReferenceObservable
{ 
	public bool Disposed { get;set; }
	public int DisposedCount { get;set; }
	public void Dispose() { Disposed = true; DisposedCount++; } 
}

public partial class ServiceProviderOnlySingleton : IWeakReferenceObservable 
{
	private readonly WeakReference _reference;

	public ServiceProviderOnlySingleton()
	{
		_reference = new WeakReference(this, false);
	}

	public bool HasReference => _reference.IsAlive;
}

public partial class ServiceProviderOnlySingletonGeneric<T> : ServiceProviderOnlySingleton { }

public partial class ServiceProviderOnlySingletonDisposable : ServiceProviderOnlySingleton, IDisposable, IDisposableObservable, IWeakReferenceObservable
{ 
	public bool Disposed { get;set; }
	public int DisposedCount { get;set; }
	public void Dispose() { Disposed = true; DisposedCount++; } 
}

public partial class WindsorOnlyTransient : IWeakReferenceObservable 
{
	private readonly WeakReference _reference;

	public WindsorOnlyTransient()
	{
		_reference = new WeakReference(this, false);
	}

	public bool HasReference => _reference.IsAlive;
}

public partial class WindsorOnlyTransientGeneric<T> : WindsorOnlyTransient { }

public partial class WindsorOnlyTransientDisposable : WindsorOnlyTransient, IDisposable, IDisposableObservable, IWeakReferenceObservable
{ 
	public bool Disposed { get;set; }
	public int DisposedCount { get;set; }
	public void Dispose() { Disposed = true; DisposedCount++; } 
}

public partial class WindsorOnlyScoped : IWeakReferenceObservable 
{
	private readonly WeakReference _reference;

	public WindsorOnlyScoped()
	{
		_reference = new WeakReference(this, false);
	}

	public bool HasReference => _reference.IsAlive;
}

public partial class WindsorOnlyScopedGeneric<T> : WindsorOnlyScoped { }

public partial class WindsorOnlyScopedDisposable : WindsorOnlyScoped, IDisposable, IDisposableObservable, IWeakReferenceObservable
{ 
	public bool Disposed { get;set; }
	public int DisposedCount { get;set; }
	public void Dispose() { Disposed = true; DisposedCount++; } 
}

public partial class WindsorOnlySingleton : IWeakReferenceObservable 
{
	private readonly WeakReference _reference;

	public WindsorOnlySingleton()
	{
		_reference = new WeakReference(this, false);
	}

	public bool HasReference => _reference.IsAlive;
}

public partial class WindsorOnlySingletonGeneric<T> : WindsorOnlySingleton { }

public partial class WindsorOnlySingletonDisposable : WindsorOnlySingleton, IDisposable, IDisposableObservable, IWeakReferenceObservable
{ 
	public bool Disposed { get;set; }
	public int DisposedCount { get;set; }
	public void Dispose() { Disposed = true; DisposedCount++; } 
}

public partial class CrossWiredTransient : IWeakReferenceObservable 
{
	private readonly WeakReference _reference;

	public CrossWiredTransient()
	{
		_reference = new WeakReference(this, false);
	}

	public bool HasReference => _reference.IsAlive;
}

public partial class CrossWiredTransientGeneric<T> : CrossWiredTransient { }

public partial class CrossWiredTransientDisposable : CrossWiredTransient, IDisposable, IDisposableObservable, IWeakReferenceObservable
{ 
	public bool Disposed { get;set; }
	public int DisposedCount { get;set; }
	public void Dispose() { Disposed = true; DisposedCount++; } 
}

public partial class CrossWiredScoped : IWeakReferenceObservable 
{
	private readonly WeakReference _reference;

	public CrossWiredScoped()
	{
		_reference = new WeakReference(this, false);
	}

	public bool HasReference => _reference.IsAlive;
}

public partial class CrossWiredScopedGeneric<T> : CrossWiredScoped { }

public partial class CrossWiredScopedDisposable : CrossWiredScoped, IDisposable, IDisposableObservable, IWeakReferenceObservable
{ 
	public bool Disposed { get;set; }
	public int DisposedCount { get;set; }
	public void Dispose() { Disposed = true; DisposedCount++; } 
}

public partial class CrossWiredSingleton : IWeakReferenceObservable 
{
	private readonly WeakReference _reference;

	public CrossWiredSingleton()
	{
		_reference = new WeakReference(this, false);
	}

	public bool HasReference => _reference.IsAlive;
}

public partial class CrossWiredSingletonGeneric<T> : CrossWiredSingleton { }

public partial class CrossWiredSingletonDisposable : CrossWiredSingleton, IDisposable, IDisposableObservable, IWeakReferenceObservable
{ 
	public bool Disposed { get;set; }
	public int DisposedCount { get;set; }
	public void Dispose() { Disposed = true; DisposedCount++; } 
}

public partial class ModelInstaller 
{
	public static void RegisterWindsor(IWindsorContainer container) 
	{
		container.Register(Component.For<WindsorOnlyTransient>().LifestyleTransient()); 
		container.Register(Component.For(typeof(WindsorOnlyTransientGeneric<>)).LifestyleTransient()); 
		container.Register(Component.For<WindsorOnlyTransientGeneric<ClosedOptions>>().LifestyleTransient()); 
		container.Register(Component.For<WindsorOnlyTransientDisposable>().LifestyleTransient()); 

		container.Register(Component.For<WindsorOnlyScoped>().LifestyleScoped()); 
		container.Register(Component.For(typeof(WindsorOnlyScopedGeneric<>)).LifestyleScoped()); 
		container.Register(Component.For<WindsorOnlyScopedGeneric<ClosedOptions>>().LifestyleScoped()); 
		container.Register(Component.For<WindsorOnlyScopedDisposable>().LifestyleScoped()); 

		container.Register(Component.For<WindsorOnlySingleton>().LifestyleSingleton()); 
		container.Register(Component.For(typeof(WindsorOnlySingletonGeneric<>)).LifestyleSingleton()); 
		container.Register(Component.For<WindsorOnlySingletonGeneric<ClosedOptions>>().LifestyleSingleton()); 
		container.Register(Component.For<WindsorOnlySingletonDisposable>().LifestyleSingleton()); 

		container.Register(Component.For<ControllerWindsorOnly>().LifestyleScoped()); 
		container.Register(Component.For<TagHelperWindsorOnly>().LifestyleScoped()); 
		container.Register(Component.For<ViewComponentWindsorOnly>().LifestyleScoped()); 


	}
		
	public static void RegisterServiceCollection(IServiceCollection services) 
	{
		services.AddTransient<ServiceProviderOnlyTransient>(); 
		services.AddTransient(typeof(ServiceProviderOnlyTransientGeneric<OpenOptions>)); 
		services.AddTransient<ServiceProviderOnlyTransientGeneric<ClosedOptions>>(); 
		services.AddTransient<ServiceProviderOnlyTransientDisposable>(); 

		services.AddScoped<ServiceProviderOnlyScoped>(); 
		services.AddScoped(typeof(ServiceProviderOnlyScopedGeneric<OpenOptions>)); 
		services.AddScoped<ServiceProviderOnlyScopedGeneric<ClosedOptions>>(); 
		services.AddScoped<ServiceProviderOnlyScopedDisposable>(); 

		services.AddSingleton<ServiceProviderOnlySingleton>(); 
		services.AddSingleton(typeof(ServiceProviderOnlySingletonGeneric<OpenOptions>)); 
		services.AddSingleton<ServiceProviderOnlySingletonGeneric<ClosedOptions>>(); 
		services.AddSingleton<ServiceProviderOnlySingletonDisposable>(); 

		services.AddScoped<ControllerServiceProviderOnly>(); 
		services.AddScoped<TagHelperServiceProviderOnly>(); 
		services.AddScoped<ViewComponentServiceProviderOnly>(); 


	}
		
	public static void RegisterCrossWired(IWindsorContainer container, IServiceCollection serviceCollection) 
	{
		container.Register(Component.For<CrossWiredTransient>().CrossWired().LifestyleTransient()); 
		container.Register(Component.For<CrossWiredTransientGeneric<OpenOptions>>().CrossWired().LifestyleTransient()); 
		container.Register(Component.For<CrossWiredTransientGeneric<ClosedOptions>>().CrossWired().LifestyleTransient()); 
		container.Register(Component.For<CrossWiredTransientDisposable>().CrossWired().LifestyleTransient()); 

		container.Register(Component.For<CrossWiredScoped>().CrossWired().LifestyleScoped()); 
		container.Register(Component.For<CrossWiredScopedGeneric<OpenOptions>>().CrossWired().LifestyleScoped()); 
		container.Register(Component.For<CrossWiredScopedGeneric<ClosedOptions>>().CrossWired().LifestyleScoped()); 
		container.Register(Component.For<CrossWiredScopedDisposable>().CrossWired().LifestyleScoped()); 

		container.Register(Component.For<CrossWiredSingleton>().CrossWired().LifestyleSingleton()); 
		container.Register(Component.For<CrossWiredSingletonGeneric<OpenOptions>>().CrossWired().LifestyleSingleton()); 
		container.Register(Component.For<CrossWiredSingletonGeneric<ClosedOptions>>().CrossWired().LifestyleSingleton()); 
		container.Register(Component.For<CrossWiredSingletonDisposable>().CrossWired().LifestyleSingleton()); 

		container.Register(Component.For<OpenOptions>().CrossWired().LifestyleSingleton());  
		container.Register(Component.For<ControllerCrossWired>().CrossWired().LifestyleScoped());  
		container.Register(Component.For<TagHelperCrossWired>().CrossWired().LifestyleScoped());  
		container.Register(Component.For<ViewComponentCrossWired>().CrossWired().LifestyleScoped());  

	}
}

public partial class ControllerWindsorOnly : Controller
{
	public ControllerWindsorOnly
	(
		WindsorOnlyTransient windsorOnlyTransient1, 
		WindsorOnlyTransientGeneric<OpenOptions> windsorOnlyTransient2, 
		WindsorOnlyTransientGeneric<ClosedOptions> windsorOnlyTransient3, 
		WindsorOnlyTransientDisposable windsorOnlyTransient4 ,
		WindsorOnlyScoped windsorOnlyScoped1, 
		WindsorOnlyScopedGeneric<OpenOptions> windsorOnlyScoped2, 
		WindsorOnlyScopedGeneric<ClosedOptions> windsorOnlyScoped3, 
		WindsorOnlyScopedDisposable windsorOnlyScoped4 ,
		WindsorOnlySingleton windsorOnlySingleton1, 
		WindsorOnlySingletonGeneric<OpenOptions> windsorOnlySingleton2, 
		WindsorOnlySingletonGeneric<ClosedOptions> windsorOnlySingleton3, 
		WindsorOnlySingletonDisposable windsorOnlySingleton4 )
	{
		if (windsorOnlyTransient1 == null) throw new ArgumentException(nameof(windsorOnlyTransient1)); 
		if (windsorOnlyTransient2 == null) throw new ArgumentException(nameof(windsorOnlyTransient2)); 
		if (windsorOnlyTransient3 == null) throw new ArgumentException(nameof(windsorOnlyTransient3)); 
		if (windsorOnlyTransient4 == null) throw new ArgumentException(nameof(windsorOnlyTransient4)); 
		if (windsorOnlyScoped1 == null) throw new ArgumentException(nameof(windsorOnlyScoped1)); 
		if (windsorOnlyScoped2 == null) throw new ArgumentException(nameof(windsorOnlyScoped2)); 
		if (windsorOnlyScoped3 == null) throw new ArgumentException(nameof(windsorOnlyScoped3)); 
		if (windsorOnlyScoped4 == null) throw new ArgumentException(nameof(windsorOnlyScoped4)); 
		if (windsorOnlySingleton1 == null) throw new ArgumentException(nameof(windsorOnlySingleton1)); 
		if (windsorOnlySingleton2 == null) throw new ArgumentException(nameof(windsorOnlySingleton2)); 
		if (windsorOnlySingleton3 == null) throw new ArgumentException(nameof(windsorOnlySingleton3)); 
		if (windsorOnlySingleton4 == null) throw new ArgumentException(nameof(windsorOnlySingleton4)); 
	}
}

public partial class TagHelperWindsorOnly : TagHelper
{
	public TagHelperWindsorOnly
	(
		WindsorOnlyTransient windsorOnlyTransient1, 
		WindsorOnlyTransientGeneric<OpenOptions> windsorOnlyTransient2, 
		WindsorOnlyTransientGeneric<ClosedOptions> windsorOnlyTransient3, 
		WindsorOnlyTransientDisposable windsorOnlyTransient4 ,
		WindsorOnlyScoped windsorOnlyScoped1, 
		WindsorOnlyScopedGeneric<OpenOptions> windsorOnlyScoped2, 
		WindsorOnlyScopedGeneric<ClosedOptions> windsorOnlyScoped3, 
		WindsorOnlyScopedDisposable windsorOnlyScoped4 ,
		WindsorOnlySingleton windsorOnlySingleton1, 
		WindsorOnlySingletonGeneric<OpenOptions> windsorOnlySingleton2, 
		WindsorOnlySingletonGeneric<ClosedOptions> windsorOnlySingleton3, 
		WindsorOnlySingletonDisposable windsorOnlySingleton4 )
	{
		if (windsorOnlyTransient1 == null) throw new ArgumentException(nameof(windsorOnlyTransient1)); 
		if (windsorOnlyTransient2 == null) throw new ArgumentException(nameof(windsorOnlyTransient2)); 
		if (windsorOnlyTransient3 == null) throw new ArgumentException(nameof(windsorOnlyTransient3)); 
		if (windsorOnlyTransient4 == null) throw new ArgumentException(nameof(windsorOnlyTransient4)); 
		if (windsorOnlyScoped1 == null) throw new ArgumentException(nameof(windsorOnlyScoped1)); 
		if (windsorOnlyScoped2 == null) throw new ArgumentException(nameof(windsorOnlyScoped2)); 
		if (windsorOnlyScoped3 == null) throw new ArgumentException(nameof(windsorOnlyScoped3)); 
		if (windsorOnlyScoped4 == null) throw new ArgumentException(nameof(windsorOnlyScoped4)); 
		if (windsorOnlySingleton1 == null) throw new ArgumentException(nameof(windsorOnlySingleton1)); 
		if (windsorOnlySingleton2 == null) throw new ArgumentException(nameof(windsorOnlySingleton2)); 
		if (windsorOnlySingleton3 == null) throw new ArgumentException(nameof(windsorOnlySingleton3)); 
		if (windsorOnlySingleton4 == null) throw new ArgumentException(nameof(windsorOnlySingleton4)); 
	}
}

public class ViewComponentWindsorOnly : ViewComponent
{
	public ViewComponentWindsorOnly
	(
		WindsorOnlyTransient windsorOnlyTransient1, 
		WindsorOnlyTransientGeneric<OpenOptions> windsorOnlyTransient2, 
		WindsorOnlyTransientGeneric<ClosedOptions> windsorOnlyTransient3, 
		WindsorOnlyTransientDisposable windsorOnlyTransient4 ,
		WindsorOnlyScoped windsorOnlyScoped1, 
		WindsorOnlyScopedGeneric<OpenOptions> windsorOnlyScoped2, 
		WindsorOnlyScopedGeneric<ClosedOptions> windsorOnlyScoped3, 
		WindsorOnlyScopedDisposable windsorOnlyScoped4 ,
		WindsorOnlySingleton windsorOnlySingleton1, 
		WindsorOnlySingletonGeneric<OpenOptions> windsorOnlySingleton2, 
		WindsorOnlySingletonGeneric<ClosedOptions> windsorOnlySingleton3, 
		WindsorOnlySingletonDisposable windsorOnlySingleton4 )
	{
		if (windsorOnlyTransient1 == null) throw new ArgumentException(nameof(windsorOnlyTransient1)); 
		if (windsorOnlyTransient2 == null) throw new ArgumentException(nameof(windsorOnlyTransient2)); 
		if (windsorOnlyTransient3 == null) throw new ArgumentException(nameof(windsorOnlyTransient3)); 
		if (windsorOnlyTransient4 == null) throw new ArgumentException(nameof(windsorOnlyTransient4)); 
		if (windsorOnlyScoped1 == null) throw new ArgumentException(nameof(windsorOnlyScoped1)); 
		if (windsorOnlyScoped2 == null) throw new ArgumentException(nameof(windsorOnlyScoped2)); 
		if (windsorOnlyScoped3 == null) throw new ArgumentException(nameof(windsorOnlyScoped3)); 
		if (windsorOnlyScoped4 == null) throw new ArgumentException(nameof(windsorOnlyScoped4)); 
		if (windsorOnlySingleton1 == null) throw new ArgumentException(nameof(windsorOnlySingleton1)); 
		if (windsorOnlySingleton2 == null) throw new ArgumentException(nameof(windsorOnlySingleton2)); 
		if (windsorOnlySingleton3 == null) throw new ArgumentException(nameof(windsorOnlySingleton3)); 
		if (windsorOnlySingleton4 == null) throw new ArgumentException(nameof(windsorOnlySingleton4)); 
	}
}

public partial class ControllerServiceProviderOnly(
	ServiceProviderOnlyTransient serviceProviderOnlyTransient1,
	ServiceProviderOnlyTransientGeneric<OpenOptions> serviceProviderOnlyTransient2,
	ServiceProviderOnlyTransientGeneric<ClosedOptions> serviceProviderOnlyTransient3,
	ServiceProviderOnlyTransientDisposable serviceProviderOnlyTransient4,
	ServiceProviderOnlyScoped serviceProviderOnlyScoped1,
	ServiceProviderOnlyScopedGeneric<OpenOptions> serviceProviderOnlyScoped2,
	ServiceProviderOnlyScopedGeneric<ClosedOptions> serviceProviderOnlyScoped3,
	ServiceProviderOnlyScopedDisposable serviceProviderOnlyScoped4,
	ServiceProviderOnlySingleton serviceProviderOnlySingleton1,
	ServiceProviderOnlySingletonGeneric<OpenOptions> serviceProviderOnlySingleton2,
	ServiceProviderOnlySingletonGeneric<ClosedOptions> serviceProviderOnlySingleton3,
	ServiceProviderOnlySingletonDisposable serviceProviderOnlySingleton4)
	: Controller;

public partial class TagHelperServiceProviderOnly : TagHelper
{
	public TagHelperServiceProviderOnly
	(
		ServiceProviderOnlyTransient serviceProviderOnlyTransient1, 
		ServiceProviderOnlyTransientGeneric<OpenOptions> serviceProviderOnlyTransient2, 
		ServiceProviderOnlyTransientGeneric<ClosedOptions> serviceProviderOnlyTransient3, 
		ServiceProviderOnlyTransientDisposable serviceProviderOnlyTransient4 ,
		ServiceProviderOnlyScoped serviceProviderOnlyScoped1, 
		ServiceProviderOnlyScopedGeneric<OpenOptions> serviceProviderOnlyScoped2, 
		ServiceProviderOnlyScopedGeneric<ClosedOptions> serviceProviderOnlyScoped3, 
		ServiceProviderOnlyScopedDisposable serviceProviderOnlyScoped4 ,
		ServiceProviderOnlySingleton serviceProviderOnlySingleton1, 
		ServiceProviderOnlySingletonGeneric<OpenOptions> serviceProviderOnlySingleton2, 
		ServiceProviderOnlySingletonGeneric<ClosedOptions> serviceProviderOnlySingleton3, 
		ServiceProviderOnlySingletonDisposable serviceProviderOnlySingleton4 )
	{
		if (serviceProviderOnlyTransient1 == null) throw new ArgumentException(nameof(serviceProviderOnlyTransient1)); 
		if (serviceProviderOnlyTransient2 == null) throw new ArgumentException(nameof(serviceProviderOnlyTransient2)); 
		if (serviceProviderOnlyTransient3 == null) throw new ArgumentException(nameof(serviceProviderOnlyTransient3)); 
		if (serviceProviderOnlyTransient4 == null) throw new ArgumentException(nameof(serviceProviderOnlyTransient4)); 
		if (serviceProviderOnlyScoped1 == null) throw new ArgumentException(nameof(serviceProviderOnlyScoped1)); 
		if (serviceProviderOnlyScoped2 == null) throw new ArgumentException(nameof(serviceProviderOnlyScoped2)); 
		if (serviceProviderOnlyScoped3 == null) throw new ArgumentException(nameof(serviceProviderOnlyScoped3)); 
		if (serviceProviderOnlyScoped4 == null) throw new ArgumentException(nameof(serviceProviderOnlyScoped4)); 
		if (serviceProviderOnlySingleton1 == null) throw new ArgumentException(nameof(serviceProviderOnlySingleton1)); 
		if (serviceProviderOnlySingleton2 == null) throw new ArgumentException(nameof(serviceProviderOnlySingleton2)); 
		if (serviceProviderOnlySingleton3 == null) throw new ArgumentException(nameof(serviceProviderOnlySingleton3)); 
		if (serviceProviderOnlySingleton4 == null) throw new ArgumentException(nameof(serviceProviderOnlySingleton4)); 
	}
}

public partial class ViewComponentServiceProviderOnly : ViewComponent
{
	public ViewComponentServiceProviderOnly
	(
		ServiceProviderOnlyTransient serviceProviderOnlyTransient1, 
		ServiceProviderOnlyTransientGeneric<OpenOptions> serviceProviderOnlyTransient2, 
		ServiceProviderOnlyTransientGeneric<ClosedOptions> serviceProviderOnlyTransient3, 
		ServiceProviderOnlyTransientDisposable serviceProviderOnlyTransient4 ,
		ServiceProviderOnlyScoped serviceProviderOnlyScoped1, 
		ServiceProviderOnlyScopedGeneric<OpenOptions> serviceProviderOnlyScoped2, 
		ServiceProviderOnlyScopedGeneric<ClosedOptions> serviceProviderOnlyScoped3, 
		ServiceProviderOnlyScopedDisposable serviceProviderOnlyScoped4 ,
		ServiceProviderOnlySingleton serviceProviderOnlySingleton1, 
		ServiceProviderOnlySingletonGeneric<OpenOptions> serviceProviderOnlySingleton2, 
		ServiceProviderOnlySingletonGeneric<ClosedOptions> serviceProviderOnlySingleton3, 
		ServiceProviderOnlySingletonDisposable serviceProviderOnlySingleton4 )
	{
		if (serviceProviderOnlyTransient1 == null) throw new ArgumentException(nameof(serviceProviderOnlyTransient1)); 
		if (serviceProviderOnlyTransient2 == null) throw new ArgumentException(nameof(serviceProviderOnlyTransient2)); 
		if (serviceProviderOnlyTransient3 == null) throw new ArgumentException(nameof(serviceProviderOnlyTransient3)); 
		if (serviceProviderOnlyTransient4 == null) throw new ArgumentException(nameof(serviceProviderOnlyTransient4)); 
		if (serviceProviderOnlyScoped1 == null) throw new ArgumentException(nameof(serviceProviderOnlyScoped1)); 
		if (serviceProviderOnlyScoped2 == null) throw new ArgumentException(nameof(serviceProviderOnlyScoped2)); 
		if (serviceProviderOnlyScoped3 == null) throw new ArgumentException(nameof(serviceProviderOnlyScoped3)); 
		if (serviceProviderOnlyScoped4 == null) throw new ArgumentException(nameof(serviceProviderOnlyScoped4)); 
		if (serviceProviderOnlySingleton1 == null) throw new ArgumentException(nameof(serviceProviderOnlySingleton1)); 
		if (serviceProviderOnlySingleton2 == null) throw new ArgumentException(nameof(serviceProviderOnlySingleton2)); 
		if (serviceProviderOnlySingleton3 == null) throw new ArgumentException(nameof(serviceProviderOnlySingleton3)); 
		if (serviceProviderOnlySingleton4 == null) throw new ArgumentException(nameof(serviceProviderOnlySingleton4)); 
	}
}

public partial class ControllerCrossWired : Controller
{
	public ControllerCrossWired
	(
		CrossWiredTransient crossWiredTransient1, 
		CrossWiredTransientGeneric<OpenOptions> crossWiredTransient2, 
		CrossWiredTransientGeneric<ClosedOptions> crossWiredTransient3, 
		CrossWiredTransientDisposable crossWiredTransient4 ,
		CrossWiredScoped crossWiredScoped1, 
		CrossWiredScopedGeneric<OpenOptions> crossWiredScoped2, 
		CrossWiredScopedGeneric<ClosedOptions> crossWiredScoped3, 
		CrossWiredScopedDisposable crossWiredScoped4 ,
		CrossWiredSingleton crossWiredSingleton1, 
		CrossWiredSingletonGeneric<OpenOptions> crossWiredSingleton2, 
		CrossWiredSingletonGeneric<ClosedOptions> crossWiredSingleton3, 
		CrossWiredSingletonDisposable crossWiredSingleton4 )
	{
		if (crossWiredTransient1 == null) throw new ArgumentException(nameof(crossWiredTransient1)); 
		if (crossWiredTransient2 == null) throw new ArgumentException(nameof(crossWiredTransient2)); 
		if (crossWiredTransient3 == null) throw new ArgumentException(nameof(crossWiredTransient3)); 
		if (crossWiredTransient4 == null) throw new ArgumentException(nameof(crossWiredTransient4)); 
		if (crossWiredScoped1 == null) throw new ArgumentException(nameof(crossWiredScoped1)); 
		if (crossWiredScoped2 == null) throw new ArgumentException(nameof(crossWiredScoped2)); 
		if (crossWiredScoped3 == null) throw new ArgumentException(nameof(crossWiredScoped3)); 
		if (crossWiredScoped4 == null) throw new ArgumentException(nameof(crossWiredScoped4)); 
		if (crossWiredSingleton1 == null) throw new ArgumentException(nameof(crossWiredSingleton1)); 
		if (crossWiredSingleton2 == null) throw new ArgumentException(nameof(crossWiredSingleton2)); 
		if (crossWiredSingleton3 == null) throw new ArgumentException(nameof(crossWiredSingleton3)); 
		if (crossWiredSingleton4 == null) throw new ArgumentException(nameof(crossWiredSingleton4)); 
	}
}

public partial class TagHelperCrossWired : TagHelper
{
	public TagHelperCrossWired
	(
		CrossWiredTransient crossWiredTransient1, 
		CrossWiredTransientGeneric<OpenOptions> crossWiredTransient2, 
		CrossWiredTransientGeneric<ClosedOptions> crossWiredTransient3, 
		CrossWiredTransientDisposable crossWiredTransient4 ,
		CrossWiredScoped crossWiredScoped1, 
		CrossWiredScopedGeneric<OpenOptions> crossWiredScoped2, 
		CrossWiredScopedGeneric<ClosedOptions> crossWiredScoped3, 
		CrossWiredScopedDisposable crossWiredScoped4 ,
		CrossWiredSingleton crossWiredSingleton1, 
		CrossWiredSingletonGeneric<OpenOptions> crossWiredSingleton2, 
		CrossWiredSingletonGeneric<ClosedOptions> crossWiredSingleton3, 
		CrossWiredSingletonDisposable crossWiredSingleton4 )
	{
		if (crossWiredTransient1 == null) throw new ArgumentException(nameof(crossWiredTransient1)); 
		if (crossWiredTransient2 == null) throw new ArgumentException(nameof(crossWiredTransient2)); 
		if (crossWiredTransient3 == null) throw new ArgumentException(nameof(crossWiredTransient3)); 
		if (crossWiredTransient4 == null) throw new ArgumentException(nameof(crossWiredTransient4)); 
		if (crossWiredScoped1 == null) throw new ArgumentException(nameof(crossWiredScoped1)); 
		if (crossWiredScoped2 == null) throw new ArgumentException(nameof(crossWiredScoped2)); 
		if (crossWiredScoped3 == null) throw new ArgumentException(nameof(crossWiredScoped3)); 
		if (crossWiredScoped4 == null) throw new ArgumentException(nameof(crossWiredScoped4)); 
		if (crossWiredSingleton1 == null) throw new ArgumentException(nameof(crossWiredSingleton1)); 
		if (crossWiredSingleton2 == null) throw new ArgumentException(nameof(crossWiredSingleton2)); 
		if (crossWiredSingleton3 == null) throw new ArgumentException(nameof(crossWiredSingleton3)); 
		if (crossWiredSingleton4 == null) throw new ArgumentException(nameof(crossWiredSingleton4)); 
	}
}

public partial class ViewComponentCrossWired : ViewComponent
{
	public ViewComponentCrossWired
	(
		CrossWiredTransient crossWiredTransient1, 
		CrossWiredTransientGeneric<OpenOptions> crossWiredTransient2, 
		CrossWiredTransientGeneric<ClosedOptions> crossWiredTransient3, 
		CrossWiredTransientDisposable crossWiredTransient4 ,
		CrossWiredScoped crossWiredScoped1, 
		CrossWiredScopedGeneric<OpenOptions> crossWiredScoped2, 
		CrossWiredScopedGeneric<ClosedOptions> crossWiredScoped3, 
		CrossWiredScopedDisposable crossWiredScoped4 ,
		CrossWiredSingleton crossWiredSingleton1, 
		CrossWiredSingletonGeneric<OpenOptions> crossWiredSingleton2, 
		CrossWiredSingletonGeneric<ClosedOptions> crossWiredSingleton3, 
		CrossWiredSingletonDisposable crossWiredSingleton4 )

	{
		if (crossWiredTransient1 == null) throw new ArgumentException(nameof(crossWiredTransient1)); 
		if (crossWiredTransient2 == null) throw new ArgumentException(nameof(crossWiredTransient2)); 
		if (crossWiredTransient3 == null) throw new ArgumentException(nameof(crossWiredTransient3)); 
		if (crossWiredTransient4 == null) throw new ArgumentException(nameof(crossWiredTransient4)); 
		if (crossWiredScoped1 == null) throw new ArgumentException(nameof(crossWiredScoped1)); 
		if (crossWiredScoped2 == null) throw new ArgumentException(nameof(crossWiredScoped2)); 
		if (crossWiredScoped3 == null) throw new ArgumentException(nameof(crossWiredScoped3)); 
		if (crossWiredScoped4 == null) throw new ArgumentException(nameof(crossWiredScoped4)); 
		if (crossWiredSingleton1 == null) throw new ArgumentException(nameof(crossWiredSingleton1)); 
		if (crossWiredSingleton2 == null) throw new ArgumentException(nameof(crossWiredSingleton2)); 
		if (crossWiredSingleton3 == null) throw new ArgumentException(nameof(crossWiredSingleton3)); 
		if (crossWiredSingleton4 == null) throw new ArgumentException(nameof(crossWiredSingleton4)); 
	}
}